config/routes.rb
Jiff::Application.routes.draw do

  match '/about' => 'static#about'
  match '/faq' => 'static#faq'
  match '/news' => 'static#news'
  match '/team' => 'static#team'
  match '/eula' => 'static#eula'
  match '/tos' => 'static#tos'
  match '/privacy' => 'static#privacy'
  match '/compete/download' => 'static#compete'
  match '/holiday' => 'static#holiday'
  match '/incentives/download' => 'static#incentives'
  
  match '/messages' => 'messages#new', :as => 'messages', :via => :get
  match '/messages' => 'messages#create', :as => 'messages', :via => :post

  resources :messages do
    collection do
      get :new
    end
  end

  resources :home do
    collection do
      get :index
    end
  end

  resources :health_plan do
    collection do
      get :index
    end
  end

  resources :partner do
    collection do
      get :index
    end
  end

  resources :employer do
    collection do
      get :index
    end
  end

  resources :static do
    collection do
      get :about
      get :news
      get :team
      get :faq
      get :careers
      get :rightnav
      get :eula
      get :privacy
      get :incentives
    end
  end

  root :to => "employer#index"

end

app/models/message.rb
class Message
  # attr_accessible :title, :body
  include ActiveAttr::Model
  
  attribute :cname
  attribute :name
  attribute :email
  attribute :title
  attribute :subject
  attribute :content
  #attribute :priority # type: Integer, default: 0
  
  #attr_accessible :name, :email, :content

  validates_presence_of :cname
  validates_presence_of :name
  validates_presence_of :title
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :subject, :maximum => 255
  validates_length_of :content, :maximum => 500
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :setup_contact
  def setup_contact
  	@message = Message.new
  end
end

app/controllers/employer_controller.rb
class EmployerController < ApplicationController
	before_filter :setup_nav
	def index
	end
	protected
	def setup_nav
		@topnav = 'employer'
	end
end

app/controllers/health_plan_controller.rb
class HealthPlanController < ApplicationController
	before_filter :setup_nav
	def index
		redirect_to employer_index_path and return
	end

	def setup_nav
		@topnav = 'health_plan'
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :setup_nav
	def index
	end

	def setup_nav
		@topnav = 'home'
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end

	def create
		@message = Message.new(params[:message])
    if @message.valid?
      # TODO send message here
      ContactMailer.new_message(@message).deliver
      respond_to do |format|
	       format.js { 
	        return render :js => "alertify.success( 'Your message was sent');" 
	       }
      end
    else
      #render "new"
      
    	@message.errors.full_messages.each do |msg|
    		respond_to do |format|
           format.js { 
            return render :js => "alertify.error('Please fill out your name and valid email');" 
           }
        end 
      end  
    end
	end
end

app/controllers/partner_controller.rb
class PartnerController < ApplicationController
	before_filter :setup_nav
	def index
	end
	
	def setup_nav
		@topnav = 'partner'
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	before_filter :setup_nav
	def about
	end

	def careers
	end

	def faq
	end

	def news
	end

	def team
	end

	def rightnav
		render :partial => "/shared/rightnav"
	end

	def setup_nav
		@topnav = 'static'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/health_plan_helper.rb
module HealthPlanHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/partner_helper.rb
module PartnerHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/employer/index.html.erb
<%= render :partial => "/shared/topnav" %>
	
	<div class="jumbotron masthead top-20">
		<div class="container">
			<div class="span2"></div>
			<div class="span4">
				<%=image_tag("img_employerpage_01.png", :alt =>"Jiff Stay Healthy", :class=> "image-center")  %>
			</div>
			<div class="span4 top-50">
				<h1> Connecting Employers to the Digital Health Ecosystem </h1>
				<br>
				<h4> Through configurable mobile &amp; web corporate wellness experiences that integrate with your benefits and incentive programs</h4>
				<br> 
				<h5 class="cap-text bottom-n5">In Partnership With</h5>
				<%=image_tag("img_logo_TowersWatson.png", :alt =>"Jiff Stay Healthy")  %>
				<br><br>
				<a href="#myAnchor" rel="" id="anchor1" class="anchorLink btn btn-info">Contact Us</a>
			</div>
		</div>
	</div>

	<div class="container top-50">
		<div class="row-fluid">
			<section class="section">
				<h2 class="text-center bottom-10"> Harness innovation </h2>
				<h4 class="text-center">The best apps, best devices, best programs for your employees in one click</h4>
				<div class="clearfix top-50">
					
						<%=image_tag("img_employerpage_02.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
					
				</div>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Give the freedom to choose </h2>
				<h4 class="text-center"> Empower and engage your employees to choose what works for them </h4>
			
		
				<div class="clearfix top-50">
					<%=image_tag("img_employerpage_03.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
				</div>

			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> It's not magic, it's logic </h2>
				<h4 class="text-center"> Real time data lets you test your way, incrementally, into programs that work for your employees </h4>
				<br><br>
				<div class="clearfix top-50">
					<%=image_tag("img_employerpage_04.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
				</div>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Configurable experiences </h2>
				<h4 class="text-center"> Mobile &amp; web experiences that are branded, customized, and engaging for your unique corporate culture </h4>
				<div class="clearfix top-50">
						<br> <br>
						<%=image_tag("img_employerpage_05.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
					
				</div>
			</section>

			<section class="section">
				<h2 class="text-center"><a name="myAnchor" id="myAnchor" style="color:white;cursor:text;">How do I sign up?</a></h2>
				<div class="span3"></div>
				<%= render :partial => "/messages/new" %>
				
			</section>
		</div>
	</div>

app/views/health_plan/index.html.erb
<%= render :partial => "/shared/topnav" %>
	<div class="jumbotron masthead top-50">
		<h2 class="text-center"> Everything you need to create exceptional digital health experiences </h2>
		<br><br>
		<div class="clearfix"> 
		
				<%=image_tag("img_healthplanpage_01.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
	
		</div>
		<br><br><br>
		<div class="container text-center"> 
			<p><a href="#myAnchor" rel="" id="anchor1" class="anchorLink btn btn-info">Contact Us</a></p>
		</div>
	</div>

	<div class="container top-50">
		<div class="row-fluid">
			<section class="section">
				<h2 class="text-center bottom-10"> Engage your consumers </h2>
				<h4 class="text-center"> Bring the beautiful user interfaces consumers expect to your clinical programs</h4>
				<div class="clearfix top-50">	
						<%=image_tag("img_healthplanpage_02.png", :alt =>"Jiff Build Better", :class => "text-center",:class=>"image-center")  %>
				</div>
				<br><br>
				
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Digitize and scale your program</h2>
				<h4 class="text-center"> Quickly virtualize your clinical programs to reach more consumers and increase impact</h4>
				<div class="clearfix top-50">
					<%=image_tag("img_healthplanpage_03.png", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
				</div>
				<br>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Connect your programs</h2>
				<h4 class="text-center"> Allow consumers to leverage popular health applications and devices in your programs</h4>
				<div class="anim">
					<div class="clearfix top-50" id="anim-connect1">			
						<%=image_tag("img_healthplanpage_04_animatedgif.gif", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
					</div>
					<div class="clearfix top-50" id="anim-connect2">			
						<%=image_tag("img_healthplanpage_04.png", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
					</div>
				</div>
				<br>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Get to market faster </h2>
				<h4 class="text-center"> Build your digital health program cheaper, faster, better</h4>
				<div class="anim2">
					<div class="clearfix top-50" id="anim-connect3">			
						<canvas id="myCanvas" width="670" height="500">
				        <!-- Insert fallback content here -->
				        Sorry, your browser doesn't support canvas technology
				    </canvas>
				    
				    
				    <script>
						var width = 670,
							height = 500,
							frames = 30, 
							currentFrame = 0,
					 
							canvas = document.getElementById("myCanvas");
							ctx = canvas.getContext("2d");
							image = new Image()
							image.src = 'assets/img_healthplanpage_05_sprite.png';
					 
						var draw = function(){
							ctx.clearRect(0, 0, width, height);
							ctx.drawImage(image, 0, height * currentFrame, width, height, 0, 0, width, height);
					 
							if (currentFrame == frames) {
							  currentFrame = 0;
							} else {
							  currentFrame++;
							}
						}
					 
						setInterval(draw, 100);
					</script>
					
					</div>
					<div class="clearfix top-50" id="anim-connect4">			
						<%=image_tag("img_healthplanpage_05.png", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
					</div>
				</div>
				<br>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> The catch </h2>
				<h4 class="text-center"> It doesn't exist. We do all the work for you. Really.</h4>
			
				<br>
			</section>

			<section class="section" id="contact">
				<h2 class="text-center"><a name="myAnchor" id="myAnchor" style="color:white;cursor:text;">Contact us for more information</a></h2>
				<div class="span3"></div>
				<%= render :partial => "/messages/new" %>
			</section>
			
		</div>
	</div>

app/views/home/index.html.erb
<div class="top-navbar top-20">
	<div class="container">
		<%=image_tag("img_Logo_Jiff_large.png", :alt =>"Jiff")  %>
		<h4> A Digital Health Technology Company </h4>
	</div>
</div>
<div class="content">
	<div class="jumbotron masthead top-20">
		<div class="container">
			<div class="span2"></div>
			<div class="span4">
				<%=image_tag("img_home_01.png", :alt =>"Jiff Stay Healthy", :class=> "image-center")  %>

			</div>
			<div class="span4 top-50">
				<h5 class="cap-text bottom-n5">Announcing</h5>
				<h1> Health Outcomes Marketplace </h1>
				<br>
				<h5 class="cap-text bottom-n5">In Partnership With</h5>
				<%=image_tag("img_logo_TowersWatson.png", :alt =>"Jiff Stay Healthy")  %>
				<br><br>
				<%= link_to 'Learn More','www.jiff.com', :class => "btn btn-info" %>
			</div>
			
		</div>
	</div>
	<div class="container top-20">
		<div class="row-fluid">
			<div class="span4">
				<img src="">
				<h3> Employer Solution </h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae eros dolor, sit amet consectetur libero. Pellentesque a velit condimentum justo elementum eleifend. Maecenas a ante vestibulum purus tincidunt egestas nec eget justo. Integer ut magna sed elit tempor imperdiet eget eget arcu. Etiam scelerisque metus id elit varius quis vestibulum mi pretium. Vivamus viverra imperdiet scelerisque. </p>
				<br>
				<p><a href="" class="btn btn-info">Learn More</a></p>
			</div>
			<div class="span4">
				<img src="">
				<h3> Health Plan Solution </h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae eros dolor, sit amet consectetur libero. Pellentesque a velit condimentum justo elementum eleifend. Maecenas a ante vestibulum purus tincidunt egestas nec eget justo. Integer ut magna sed elit tempor imperdiet eget eget arcu. Etiam scelerisque metus id elit varius quis vestibulum mi pretium. Vivamus viverra imperdiet scelerisque.</p>
				<br>
				<p><a href="" class="btn btn-info">Learn More</a></p>
			</div>
			<div class="span4">
				<img src="">
				<h3> Digital Health Partner </h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae eros dolor, sit amet consectetur libero. Pellentesque a velit condimentum justo elementum eleifend. Maecenas a ante vestibulum purus tincidunt egestas nec eget justo. Integer ut magna sed elit tempor imperdiet eget eget arcu. Etiam scelerisque metus id elit varius quis vestibulum mi pretium. Vivamus viverra imperdiet scelerisque. </p>
				<br>
				<p><a href="" class="btn btn-info">Learn More</a></p>
			</div>
		</div>
	</div>
</div>
<div class="news container">
	<div class="row-fluid">
		<div class="span4">
			<%=image_tag("img_press_Forbes.png", :alt =>"Jiff", :class =>"top-20")  %>
		</div>
		<div class="span4">
			<%=image_tag("img_press_VentureBeat.png", :alt =>"Jiff", :class => "top-20")  %>
		</div>
		<div class="span4">
			<%=image_tag("img_press_HIMSS.png", :alt =>"Jiff")  %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jiff</title>
  <meta name="description" content="Connected Health. Better Outcomes.">
	<meta name="keywords" content="Jiff, digital health">
	<META NAME="ROBOTS" CONTENT="Jiff, Connected Health. Better Outcomes">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta name="HandheldFriendly" content="True" />
	<meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Kreon:300,400,700' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'jiff.ico' %>

  <%= yield(:head) %>

</head>
<body>
<div class="wrap-all">
	<%= yield %>
</div>
<script type="text/javascript">
	$(document).ready(function(){
	    $('[data-slidepanel]').slidepanel({
	        orientation: 'right',
	        mode: 'push'
	    });
	});
</script>
</body>
</html>

app/views/messages/_new.html.erb
	<%= form_for Message.new, :url => messages_path, :remote => true do |f| %>
	<!-- 	<div class="clearfix">
		  <%# if @message.errors.any? %>
		    <div class="error_messages">
		      <h2><%#= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
		      <ul>
		      <%# @message.errors.full_messages.each do |msg| %>
		        <li><%#= msg %></li>
		      <%# end %>
		      </ul>
		    </div>
		  <%# end %>
		</div> -->
		<div class="top-20">
			
			<div class="span3">
				<div class="clearfix">
			    <%= f.text_field :cname, :placeholder => "Your company name", :class =>"input-large" %>
			  </div>
			  <div class="clearfix">
			    <%= f.text_field :name, :placeholder => "Your full name", :class =>"input-large" %>
			  </div>
			  <div class="clearfix">
			      <%= f.text_field :title, :placeholder => "Your title", :class =>"input-large" %>
		    </div>
			  <div class="clearfix">
			    <%= f.text_field :email, :placeholder => "Your work email", :class =>"input-large" %>
			  </div>
			  
		  </div>
		  <div class="span3">


		    <%= f.text_area :content, :size => "80x8", :placeholder => "Questions, messages, or topics you are interested in...", :class=>"input-large" %>
		  </div>
		  <div>
		  	<%#= f.select :subject, options_for_select(["A","B","C"]), {:prompt => "Select subject"}, :class => "select-subject"%>
		  </div>
		</div>
		<br>
		<div class="clearfix text-center top-20">
			<br>
			<p>If you have troubles with the form above, please send us an email directly to <a href="mailto:partners@jiff.com" > partners@jiff.com </a> </p>
			<br>
		</div>
	  <div class="actions clearfix text-center">
	  	<%= f.submit "      Send      ", :class => "btn btn-warning top-10" %>
	 	</div>
	<% end %>

app/views/partner/index.html.erb
<%= render :partial => "/shared/topnav" %>
	<div class="jumbotron masthead top-50">
		<h2 class="text-center"> The Health Outcomes Marketplace: <br>Your wellness product. Dozens of employers.<br>Millions of consumers. Enough said. </h2>
		<br> <br>
		<div class="clearfix">
			<%=image_tag("img_partnerpage_01.png", :alt =>"Jiff Stay Healthy", :class => "image-center")  %>
		</div>
	</div>

	<div class="container top-50">
		<div class="row-fluid">
			<section class="section">
				<h2 class="text-center bottom-10"> Get paid </h2>
				<h4 class="text-center"> Tap into employer and consumer wellness dollars by joining the Health Outcomes Marketplace<sup>TM</sup></h4>
				<div class="clearfix top-50">	
						<%=image_tag("img_partnerpage_02.png", :alt =>"Jiff Build Better", :class => "text-center",:class=>"image-center")  %>
				</div>
				<br><br>
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Connect easily</h2>
				<h4 class="text-center"> Connect your awesome program, app or device to our platform via our API </h4>
				<div class="anim">
					<div class="clearfix top-50" id="anim-connect1">			
						<%=image_tag("img_healthplanpage_04_animatedgif.gif", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
					</div>
					<div class="clearfix top-50" id="anim-connect2">			
						<%=image_tag("img_healthplanpage_04.png", :alt =>"Jiff Stay Healthy", :class=>"image-center")  %>
					</div>
				</div>
				<br><br>		
			</section>

			<section class="section">
				<h2 class="text-center bottom-10"> Current integrations </h2>
				<h4 class="text-center"> Invest more in health outcomes and less in sales and marketing </h4>
				<div class="clearfix top-50">	
						<%=image_tag("img_integrations.png", :alt =>"Jiff Build Better", :class => "text-center",:class=>"image-center")  %>
				</div>
				<br><br>		
			</section>

			<section class="section" id="contact">
				<h2 class="text-center"> Apply to the marketplace now </h2>
				<div class="span3"> </div>
				<%= render :partial => "/messages/new" %>
			</section>
			
		</div>
	</div>

app/views/shared/_contact.html.erb
<section class="section5">
  <h2 class="text-center"> Contact us for more information </h2>
  <br>
  <form>
    <div class="clearfix">
      <div class="span3"></div>
      <div class="span3">
        <div class="clearfix"> 
          <input class="input-large" placeholder="Company name">
        </div>
        <div class="clearfix">
          <input class="input-large top-5" placeholder="Your full name">
        </div>
        <div class="clearfix">
          <input class="input-large top-5" placeholder="Your title">
        </div>
        <div class="clearfix">
          <input class="input-large top-5" placeholder="Your work email">
        </div>
        
      </div>
      <div class="span3">
        <textarea rows="8" cols="80" placeholder="Questions messages or topics you are interested in..." class="input-large">
</textarea>
      </div>
      
    </div>
    <br>
    <div class="clearfix text-center">
      <a class="btn btn-warning width-small"> Send</a>
    </div>
  </form>
</section>

app/views/shared/_footer.html.erb
<footer class="footer">
		<div class="container">
			<div class="social-media">
				<li> facebook</li>
				<li> twitter </li>
			</div>
			<div class="clearfix bottom-n10">
				<ul class="footer-links1">
					<li> <%= link_to "About Us", about_static_index_path %> </li>
					<li class="muted">&middot;</li>
					<li> <%= link_to "News & Press", news_static_index_path %> </li>
					<li class="muted">&middot;</li>
					<li> <%= link_to "Team", team_static_index_path %>  </li>
					<li class="muted">&middot;</li>
					<li> <%= link_to "Careers", team_static_index_path %>  </li>
					<li class="muted">&middot;</li>
					<li> <%= link_to "FAQ", faq_static_index_path %>  </li>
				</ul>
			</div>
			<div class="clearfix">
				<ul class="footer-links2">
					<li> Healthcare in a Jiff </li>
					<li class="muted"> &middot; </li>
					<li> &copy;2013 Jiff, Inc </li>
					<li class="muted"> &middot; </li>
					<li> HIPAA Compliant </li>
					<li class="muted"> &middot; </li>
					<li> Made in Palo Alto </li>
				</ul>
			</div>
		</div>
	</footer>
	

app/views/shared/_leftnav.html.erb
<div class="span3">
	<ul class="nav">
		<li> <%= link_to "About Us", about_static_index_path %></li>
		<li class="top-5"> <%= link_to "News & Press", news_static_index_path %> </li>
		<li class="top-5"> <%= link_to "Team", team_static_index_path %> </li>
		<li class="top-5"> <%= link_to "Careers", careers_static_index_path %> </li>
		<li class="top-5"> <%= link_to "FAQ", faq_static_index_path %> </li>
	</ul>
</div>

app/views/shared/_rightnav.html.erb
<div class="clearfix">
	<ul class="nav right-links">
	  <li class="<%= 'active' if @topnav == 'employer' %>"> <%= link_to "EMPLOYERS".html_safe, employer_index_path, :alt =>"jiff and employer" %>   <!-- <a href="#">EMPLOYER <span> SOLUTION</span> </a> --></li>
<!-- 	  <li class="<%# 'active' if @topnav == 'health_plan' %>"> <%# link_to "HEALTH PLANS".html_safe, health_plan_index_path, :alt =>"jiff health plan" %></li>
 -->	  <li class="<%= 'active' if @topnav == 'partner' %>"> <%= link_to " DIGITAL HEALTH PARTNERS".html_safe, partner_index_path, :alt =>"jiff and partner" %></li>
	</ul>
</div>

<div class="clearfix footer">
	<ul class="footer-links top-20">
		<li> <%= link_to "About Us", about_path %> </li>
		<li class="top-5"> <%= link_to "News", news_path %> </li>
		<li class="top-5"> <%= link_to "FAQ", faq_path %> </li>
	</ul>
</div>

<div class="clearfix social-media left-20 top-20">
	<ul>
		<li> <a href="https://twitter.com/JiffInc" class="footer-twitter" target="_blank"> </a></li>
	</ul>
</div>

<div class="clearfix logo-footer left-20 top-20">
	<ul>
		<li> <%=image_tag("img_logo_sidenav.png", :alt =>"Jiff, HIPPA Compliant") %></li>
	</ul>
</div>

<div class='clearfix contact-us top-20 left-20'>
	<p class='left-10'> Contact Info</p>
	<ul class='top-10'>
		<li> Business Contact <br> <a href="mailto:partners@jiff.com" > partners@jiff.com </a></li>
		<li class='top-10'> Press Contact <br> <a href="mailto:press@jiff.com" > press@jiff.com </a></li>
	</ul>
</div>

app/views/shared/_topnav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div>
        <ul class="nav pull-right top-links">
          <li class="<%= 'active' if @topnav == 'employer' %>"> <%= link_to "EMPLOYERS".html_safe, employer_index_path, :alt =>"jiff and employer" %> </li>
<!--           <li class="<%# 'active' if @topnav == 'health_plan' %>"> <%# link_to "HEALTH PLANS".html_safe, health_plan_index_path, :alt =>"jiff health plan" %></li>
 -->          <li class="<%= 'active' if @topnav == 'partner' %>"> <%= link_to "PARTNERS".html_safe, partner_index_path, :alt =>"jiff and partner" %></li>
          <li> <a href="http://blog.jiff.com/"> BLOG </a> </li>
          <li class="menu"><a href="/static/rightnav" data-slidepanel="panel">MENU </a></li>
        </ul>
        <h3 class="muted top-10"><%= link_to image_tag("img_logoandtagline_Jiff.png", :alt =>"Jiff"), employer_index_path  %>  </h3>
      </div>
    </div>
  </div>
</div>